export default  Theme = {
  colors:{
    lightBlue:'#009688',
    green:'#43a047',
    violet:'#5c6bc0',
    purple:'#ab47bc',
    white:'#ffffff',
    darkGray:'#424242',
    inputBackgroundColor:'#EEEEEE',
    redBalehu:'#e63d30',
    twitterBlue:'#5c9eff',
    PromotionBlue:'#00acc1',
    skyBlue:'#1e88e5',
    blue:'#42a5f5',
    warmGrey:'#9e9e9e',
    greyishBrown:'#424242',
  },
  fontFamily:{
    bold: 'NunitoSans-Bold',
    regular: 'NunitoSans-Regular',
    semiBold:'NunitoSans-SemiBold',
  },
  fontSize:{
    maxLarge: 40,
    superLarge: 35,
    extraLarge: 32,
    large:30,
    semiLarge:22,
    midLarge: 23,
    title: 20,
    header: 18,
    itemHeader: 17,
    medium: 16,
    normal: 15,
    midregular: 14,
    smallMedium:13,
    small: 12,
    midSmall:10.5,
    semiSmall:9,
    tiny:7
  }
}
